name: Release Go Binaries

on:
  release:
    types: [created] 

permissions:
    contents: write
    packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:  
          - goos: windows
            goarch: arm64 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Release Binaries
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: "quay-yala"
          extra_files: README.md